const genres = [
  // Fiction
  "Mystery & Crime",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Historical Fiction",
  "Literary Fiction",
  "Thriller",
  "Horror",
  "Humor",
  "Children's Fiction",

  // Subgenres within Fiction (consider including these as options within their respective parent genres)
  "Action Adventure Mystery",
  "Cozy Mystery",
  "Crime Thriller",
  "Detective Fiction",
  "Historical Mystery",
  "Legal Thriller",
  "Police Procedural",
  "Psychological Thriller",
  "Spy Thriller",
  "Alien Invasion",
  "Dystopian",
  "Space Opera",
  "Cyberpunk",
  "Military Science Fiction",
  "High Fantasy",
  "Epic Fantasy",
  "Dark Fantasy",
  "Sword and Sorcery",
  "Urban Fantasy",
  "Historical Romance",
  "Contemporary Romance",
  "Paranormal Romance",

  // Non-Fiction
  "History",
  "Biography",
  "Self-Help",
  "Science",
  "Art",
  "Social Sciences",
  "Travel",
  "Food & Cooking",
  "Religion & Spirituality",
  "Memoir",
  "Business & Economics",

  "Adventure",
  "Classics",
  "Coming-of-Age",
  "Mystery",
  "Tragedy",
  "Post-Apocalyptic",
  "Drama",
];

export default genres;
